repos:
    - repo: https://github.com/psf/black
      rev: 21.12b0
      hooks:
        - id: black
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.5.0
      hooks:
        - id: check-added-large-files
    - repo: local
      hooks:
        - id: tag stuff
          name: tag stuff
          always_run: true
          stages: [post-commit]
          entry: 'python'
          args: ['tagger.py']
          language: system
          types: ['python']